apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPodRequests
metadata:
  name: pods-must-have-requests
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  enforcementAction: deny