name: OPA-Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  conftest:
    runs-on: ubuntu-latest
    container: openpolicyagent/conftest:latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Check DEMO ALL TASKS
        run: conftest test --all-namespaces -o github -p practice/demo/solutions practice/demo/input.json

      - name: Check DOCKERFILE TASK 1
        run: conftest test --all-namespaces -o github -p practice/dockerfile/task1 practice/dockerfile/task1/samples

      - name: Check DOCKERFILE TASK 2
        run: conftest test --all-namespaces -o github -p practice/dockerfile/task2 practice/dockerfile/task2/samples
      
      - name: Check KUBERNETES TASK 1
        run: conftest test --all-namespaces -o github -p practice/k8s practice/k8s/example/3-bad-pod.yaml
